import { ROLE_IDS } from '~/utils/roles'
import { PERMISSIONS } from '~/utils/permissions'

export const ROLE_PERMISSIONS = {
  [ROLE_IDS.ADMIN]: [
    PERMISSIONS.EMPLOYEE_VIEW,
    PERMISSIONS.EMPLOYEE_CREATE,
    PERMISSIONS.EMPLOYEE_UPDATE,
    PERMISSIONS.EMPLOYEE_DELETE
  ],

  [ROLE_IDS.MANAGER]: [
    PERMISSIONS.EMPLOYEE_VIEW,
    PERMISSIONS.EMPLOYEE_CREATE,
    PERMISSIONS.EMPLOYEE_UPDATE
  ],

  [ROLE_IDS.CASHIER]: [PERMISSIONS.EMPLOYEE_VIEW],

  [ROLE_IDS.BARISTA]: [PERMISSIONS.EMPLOYEE_VIEW],

  [ROLE_IDS.WAITER]: [PERMISSIONS.EMPLOYEE_VIEW]
}